apiVersion: v1
kind: Pod
metadata:
  name: mypod-live
  labels:
    app: test
    env: dev
spec:
  containers:
    - image: k8s.gcr.io/echoserver:1.10
      name: echoserver
      ports:
        - containerPort: 8080
          protocol: TCP
      livenessProbe:
        httpGet:
          path: /
          port: 8080
