apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mypod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mypod
  template:
    metadata:
      labels:
        app: mypod
    spec:
      containers:
      - name: mypod2
        image: k8s.gcr.io/echoserver:1.10
        ports:
        - containerPort: 8080
