apiVersion: v1
kind: ReplicationController
metadata:
  name: myreplicatedpod
spec:
  replicas: 3
  selector:
    app: mypod
  template:
    metadata:
      labels:
        app: mypod
    spec:
      containers:
      - name: myreplicatedcontainer
        image: k8s.gcr.io/echoserver:1.10
        ports:
        - containerPort: 8080