apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    app: myapp
    env: dev
spec:
 nodeSelector:
   env: dev
 containers:
 - image: k8s.gcr.io/echoserver:1.10
   name: echoserver
   ports:
   - containerPort: 8080
     protocol: TCP